version: "3.7"
services:
  proxy:
    image: wallbox_proxy
    network_mode: host
    build:
      network: host
      context: .
      dockerfile: docker/proxy/dev.Dockerfile
  mpd:
    image: wallbox_mpd
    network_mode: host
    build:
      network: host
      context: .
      dockerfile: docker/mpd/Dockerfile
    devices:
      - /dev/snd
    volumes:
      - "${MPD_MUSIC_DIR:-music}:/var/lib/mpd/music"
