version: "3.7"
services:
  mpd:
    image: wallbox_mpd
    build:
      network: host
      context: .
      dockerfile: mpd/Dockerfile
    ports:
      - "6600:6600"
    devices:
      - /dev/snd
    volumes:
      - "/home/samuel/Music:/var/lib/mpd/music"
      #- "/mnt/c/TorrentFiles/music/:/var/lib/mpd/music"
  server:
    image: wallbox_server
    build:
      network: host
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MPD_HOST=mpd
    depends_on:
      - mpd
  client:
    image: wallbox_client
    build:
      network: host
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - mpd
    environment:
      - MPD_HOST=mpd
  angular-client:
    image: wallbox_angular-client
    build:
      network: host
      context: .
      dockerfile: angular-client/Dockerfile
